sudo: false
dist: trusty
language: python
services: docker

python:
  - 3.6

install:
    - pip install jinja2
    - for i in 2.7 3.5 3.6 ; do docker pull pymor/python:$i ; done

script:
    - make check
    # fail if index is not up-to-date
    - make index && git diff --exit-code

notifications:
  email:
    on_success: change
    on_failure: change
    on_start: never

branches:
  except:
    - gh-pages
