sudo: false
dist: trusty
language: python
services: docker

python:
  - 3.6


script:
    - make check

# runs independent of 'script' failure/success
#after_script:
    #- ${DOCKER_RUN} /src/.ci/travis/after_script.bash

notifications:
  email:
    on_success: change
    on_failure: change
    on_start: never

branches:
  except:
    - gh-pages
